FctBundle\Entity\Alumno:
    type: entity
    table: alumnos
    repositoryClass: FctBundle\Repository\AlumnoRepository
    indexes:
        FK_AL_CF:
            columns:
                - COD_CICLO
        FK_AL_CF2:
            columns:
                - PROVINCIA_ALU
    uniqueConstraints:
        NIF_ALU:
            columns:
                - NIF_ALU
        NICKNAME_ALU:
            columns:
                - NICKNAME_ALU
    id:
        idAlu:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_ALU
            generator:
                strategy: IDENTITY
    fields:
        nifAlu:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: NIF_ALU
        nombreAlu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NOMBRE_ALU
        apellido1Alu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APELLIDO1_ALU
        apellido2Alu:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APELLIDO2_ALU
        fotografiaAlu:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FOTOGRAFIA_ALU
        nicknameAlu:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: NICKNAME_ALU
        direccionAlu:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: DIRECCION_ALU
        poblacionAlu:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: POBLACION_ALU
        cpostalAlu:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CPOSTAL_ALU
        telfFijoAlu:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TELF_FIJO_ALU
        telfMovilAlu:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TELF_MOVIL_ALU
        emailAlu:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: EMAIL_ALU
    manyToOne:
        codCiclo:
            targetEntity: Ciclo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                COD_CICLO:
                    referencedColumnName: ID_CICLO
            orphanRemoval: false
        provinciaAlu:
            targetEntity: Provincia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PROVINCIA_ALU:
                    referencedColumnName: ID_PROVINCIA
            orphanRemoval: false
    lifecycleCallbacks: {  }
