FctBundle\Entity\Ciclo:
    type: entity
    table: ciclos
    repositoryClass: FctBundle\Repository\CicloRepository
    uniqueConstraints:
        CODIGO:
            columns:
                - CODIGO
    id:
        idCiclo:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_CICLO
            generator:
                strategy: IDENTITY
    fields:
        codigo:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: CODIGO
        nombreCiclo:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: NOMBRE_CICLO
        grado:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: GRADO
        horasfct:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: HORASFCT
    lifecycleCallbacks: {  }
