FctBundle\Entity\Empresa:
    type: entity
    table: empresas
    indexes:
        FK_EMP:
            columns:
                - PROVINCIA_EMP
    uniqueConstraints:
        CIF_EMP:
            columns:
                - CIF_EMP
    id:
        idEmp:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_EMP
            generator:
                strategy: IDENTITY
    fields:
        cifEmp:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: CIF_EMP
        nombreEmp:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NOMBRE_EMP
        tutorEmp:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: TUTOR_EMP
        direccionEmp:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: DIRECCION_EMP
        poblacionEmp:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: POBLACION_EMP
        cpostalEmp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CPOSTAL_EMP
        telfFijoEmp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TELF_FIJO_EMP
        telfMovilEmp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TELF_MOVIL_EMP
        emailEmp:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: EMAIL_EMP
    manyToOne:
        provinciaEmp:
            targetEntity: Provincia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PROVINCIA_EMP:
                    referencedColumnName: ID_PROVINCIA
            orphanRemoval: false
    lifecycleCallbacks: {  }
