FctBundle\Entity\Fct:
    type: entity
    table: fct
    repositoryClass: FctBundle\Repository\FctRepository
    indexes:
        FK_FCT:
            columns:
                - ID_PROF
        FK_FCT2:
            columns:
                - ID_EMP
        FK_FCT3:
            columns:
                - ID_ALU
    id:
        idFct:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_FCT
            generator:
                strategy: IDENTITY
    fields:
        anio:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ANIO
    manyToOne:
        idProf:
            targetEntity: Profesor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_PROF:
                    referencedColumnName: ID_PROF
            orphanRemoval: false
        idEmp:
            targetEntity: Empresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_EMP:
                    referencedColumnName: ID_EMP
            orphanRemoval: false
        idAlu:
            targetEntity: Alumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_ALU:
                    referencedColumnName: ID_ALU
            orphanRemoval: false
    lifecycleCallbacks: {  }
