FctBundle\Entity\Profesor:
    type: entity
    table: profesores
    uniqueConstraints:
        NIF_PROF:
            columns:
                - NIF_PROF
        NICKNAME_PROF:
            columns:
                - NICKNAME_PROF
        PASSWORD_PROF:
            columns:
                - PASSWORD_PROF
    id:
        idProf:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_PROF
            generator:
                strategy: IDENTITY
    fields:
        nifProf:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: NIF_PROF
        nombreProf:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NOMBRE_PROF
        apellido1Prof:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APELLIDO1_PROF
        apellido2Prof:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APELLIDO2_PROF
        fotografiaProf:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FOTOGRAFIA_PROF
        nicknameProf:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: NICKNAME_PROF
        telfFijoProf:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TELF_FIJO_PROF
        telfMovilProf:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TELF_MOVIL_PROF
        emailProf:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: EMAIL_PROF
        passwordProf:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
            column: PASSWORD_PROF
        rolProf:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: ROL_PROF
    lifecycleCallbacks: {  }
