FctBundle\Entity\Provincia:
    type: entity
    table: provincias
    id:
        idProvincia:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_PROVINCIA
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: NOMBRE
    lifecycleCallbacks: {  }
