login:
    path: /login
    defaults: { _controller: FctBundle:Profesor:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
sign_up:
    path: /profesores/create_profesor
    defaults: { _controller: FctBundle:Profesor:create_profesor }

fct_homepage:
    path:     /
    defaults: { _controller: FctBundle:Default:index }

fct_index_alumno:
    path: /alumnos
    defaults: { _controller: FctBundle:Alumno:index }

fct_create_alumno:
    path: /alumnos/create_alumno
    defaults: { _controller: FctBundle:Alumno:create_alumno }
    
fct_delete_alumno:
    path: /alumnos/delete_alumno/{id_alu}
    defaults: { _controller: FctBundle:Alumno:delete_alumno }
    
fct_index_ciclo:
    path: /ciclos
    defaults: { _controller: FctBundle:Ciclo:index }

fct_create_ciclo:
    path: /ciclos/create_ciclo
    defaults: { _controller: FctBundle:Ciclo:create_ciclo }
    
fct_delete_ciclo:
    path: /ciclos/delete_ciclo/{id_ciclo}
    defaults: { _controller: FctBundle:Ciclo:delete_ciclo }

