login:
    path: /login
    defaults: { _controller: FctBundle:Profesor:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
sign_up:
    path: /profesores/create_profesor
    defaults: { _controller: FctBundle:Profesor:create_profesor }
    
create_alumno:
    path: /alumnos/create_alumno
    defaults: { _controller: FctBundle:Alumno:create_alumno }

fct_homepage:
    path:     /
    defaults: { _controller: FctBundle:Default:index }
