login:
    path: /login
    defaults: { _controller: FctBundle:Profesor:login }
    
login_check:
    path: /login_check
    
logout:
    path: /logout
    
sign_up:
    path: /profesores/create_profesor
    defaults: { _controller: FctBundle:Profesor:create_profesor }

fct_homepage:
    path:     /
    defaults: { _controller: FctBundle:Default:index }
    
fct_index_profesor:
    path: /profesores
    defaults: { _controller: FctBundle:Profesor:index }
    
fct_delete_profesor:
    path: /profesores/delete_profesor/{id_prof}
    defaults: { _controller: FctBundle:Profesor:delete_profesor }

fct_index_alumno:
    path: /alumnos
    defaults: { _controller: FctBundle:Alumno:index }

fct_create_alumno:
    path: /alumnos/create_alumno
    defaults: { _controller: FctBundle:Alumno:create_alumno }
    
fct_delete_alumno:
    path: /alumnos/delete_alumno/{id_alu}
    defaults: { _controller: FctBundle:Alumno:delete_alumno }
    
fct_edit_alumno:
    path: /alumnos/edit_Alumno/{id_alu}
    defaults: { _controller: FctBundke:Alumno:edit_alumno }
    
fct_index_ciclo:
    path: /ciclos
    defaults: { _controller: FctBundle:Ciclo:index }

fct_create_ciclo:
    path: /ciclos/create_ciclo
    defaults: { _controller: FctBundle:Ciclo:create_ciclo }
    
fct_delete_ciclo:
    path: /ciclos/delete_ciclo/{id_ciclo}
    defaults: { _controller: FctBundle:Ciclo:delete_ciclo }
    
fct_edit_ciclo:
    path: /ciclos/edit_ciclo/{id_ciclo}
    deafults: { _controller: FctBundle:Ciclo:edit_ciclo }
    
fct_index_empresa:
    path: /empresas
    defaults: { _controller: FctBundle:Empresa:index }
    
fct_create_empresa:
    path: /empresas/create_empresa
    defaults: { _controller: FctBundle:Empresa:create_empresa }
    
fct_delete_empresa:
    path: /empresas/delete_empresa/{id_emp}
    defaults: { _controller: FctBundle:Empresa:delete_empresa }
    
fct_edit_empresa:
    path: /empresas/edit_empresa/{id_emp}
    defaults: { _controller: FctBundle:Empresa:edit_empresa }
    
fct_index_fct:
    path: /fct
    defaults: { _controller: FctBundle:Fct:index }
    
fct_create_fct:
    path: /fct/create_fct
    defaults: { _controller: FctBundle:Fct:create_fct }
    
fct_delete_fct:
    path: /fct/delete_fct/{id_fct}
    defaults: { _controller: FctBundle:Fct:delete_fct }
    
fct_edit_fct:
    path: /fct/edit_fct/{id_fct}
    defaults: { _controller: FctBundle:Fct:edit_fct }

