<?php

namespace AppBundle\Repository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FctRepository extends \Doctrine\ORM\EntityRepository
{
}
